[versions]
compose = "1.0.1"
dagger = "2.38.1"
kotlin = "1.5.21"
espresso = "3.4.0"
androidXTest = "1.4.0"
compileSdk = "31"
minSdk = "21"
targetSdk = "30"
spotless = "5.14.2"
dependencyUpdates = "0.39.0"

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
dependencyUpdates = { id = "com.github.ben-manes.versions", version.ref = "dependencyUpdates" }

[libraries]
androidx-activityCompose = "androidx.activity:activity-compose:1.3.1"
androidx-appcompat = "androidx.appcompat:appcompat:1.3.1"
androidx-lifecycle-livedata = "androidx.lifecycle:lifecycle-livedata-ktx:2.3.1"

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
compose-navigation = "androidx.navigation:navigation-compose:2.4.0-alpha07"

dagger-runtime = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-hilt-runtime = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
dagger-hilt-navigationCompose = "androidx.hilt:hilt-navigation-compose:1.0.0-alpha03"

autoService = "com.google.auto.service:auto-service:1.0"

# Espresso testing
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
espresso-runner = { module = "androidx.test:runner", version.ref = "androidXTest" }
espresso-rules = { module = "androidx.test:rules", version.ref = "androidXTest" }
espresso-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidXTest" }
compose-testing = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }

# Gradle plugins
plugin-androidTools = "com.android.tools.build:gradle:7.0.1"
plugin-hiltAndroidGradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
plugin-kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-mavenPublish = "com.vanniktech:gradle-maven-publish-plugin:0.17.0"
plugin-dokka = "org.jetbrains.dokka:dokka-gradle-plugin:1.5.0"

[bundles]
daggerRuntimes = ["dagger-runtime", "dagger-hilt-runtime"]
daggerCompilers = ["dagger-compiler", "dagger-hilt-compiler"]
espressoCore = ["espresso-core", "espresso-runner", "espresso-rules"]
